import { useId, useState } from 'react';
import type { WorkItem, WorkStatus } from '../types/work';
import { WORK_STATUSES } from '../types/work';
import { computeSessionActiveMs, computeWorkItemActiveMs, formatDuration } from '../lib/timer';

export default function SessionSummary({ item, onSave }: { item: WorkItem; onSave: (updates: { status: WorkStatus; outcome?: string; notes?: string }) => void }) {
  const [status, setStatus] = useState<WorkStatus>(item.status);
  const [outcome, setOutcome] = useState(item.outcome ?? ''); const [notes, setNotes] = useState(item.notes ?? '');
  const statusId = useId(); const outcomeId = useId(); const notesId = useId();
  const session = item.sessions[item.sessions.length - 1];
  return <div className="overlay overlay-center" role="dialog" aria-modal="true" aria-labelledby="session-summary-title"><div className="modal" style={{ width: 480 }}><div className="mono" style={{ fontSize: 11, color: 'var(--text-faint)' }}>{item.workId}</div><h2 id="session-summary-title" style={{ fontSize: 18, margin: '4px 0 20px' }}>Work Session Summary</h2><div style={{ fontWeight: 600 }}>{item.taskTitle}</div><p style={{ color: 'var(--text-muted)', fontSize: 13 }}>This session is complete. The Work Item can remain In Progress and be continued later.</p><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14, margin: '16px 0 20px' }}><Stat label="Session active time" value={formatDuration(computeSessionActiveMs(session, new Date()))} /><Stat label="Total active time" value={formatDuration(computeWorkItemActiveMs(item, new Date()))} /></div><label className="field-label" htmlFor={statusId}>Work Item status</label><select id={statusId} className="select" value={status} onChange={(e) => setStatus(e.target.value as WorkStatus)}>{WORK_STATUSES.map((value) => <option key={value}>{value}</option>)}</select><label className="field-label" htmlFor={outcomeId} style={{ marginTop: 14 }}>Outcome <span className="field-hint">optional</span></label><textarea id={outcomeId} className="textarea" value={outcome} onChange={(e) => setOutcome(e.target.value)} /><label className="field-label" htmlFor={notesId} style={{ marginTop: 14 }}>Notes <span className="field-hint">optional</span></label><textarea id={notesId} className="textarea" value={notes} onChange={(e) => setNotes(e.target.value)} /><div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 22 }}><button onClick={() => onSave({ status, outcome: outcome || undefined, notes: notes || undefined })} className="btn btn-primary">Save &amp; Close</button></div></div></div>;
}
function Stat({ label, value }: { label: string; value: string }) { return <div><div style={{ fontSize: 11, color: 'var(--text-faint)' }}>{label}</div><div className="mono" style={{ fontSize: 18, fontWeight: 600 }}>{value}</div></div>; }
