import { cloneElement, isValidElement, useId, useState, type ReactElement, type ReactNode } from 'react';
import { v4 as uuid } from 'uuid';
import type { WorkCategory, WorkItem, WorkLink, WorkPriority } from '../types/work';
import { WORK_CATEGORIES, WORK_PRIORITIES } from '../types/work';

interface Props {
  workId: string; // pre-generated by the caller (needs existing ids for today)
  date: string;
  onCancel: () => void;
  onCreate: (item: WorkItem) => void;
}

export default function WorkPlanForm({ workId, date, onCancel, onCreate }: Props) {
  const [project, setProject] = useState('');
  const [client, setClient] = useState('');
  const [environment, setEnvironment] = useState('');
  const [category, setCategory] = useState<WorkCategory | ''>('');
  const [taskTitle, setTaskTitle] = useState('');
  const [description, setDescription] = useState('');
  const [priority, setPriority] = useState<WorkPriority>('Medium');
  const [technologies, setTechnologies] = useState('');
  const [ticketId, setTicketId] = useState('');
  const [links, setLinks] = useState<WorkLink[]>([]);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const addLink = () => setLinks((prev) => [...prev, { id: uuid(), type: '', url: '' }]);
  const updateLink = (id: string, field: 'type' | 'url', value: string) =>
    setLinks((prev) => prev.map((l) => (l.id === id ? { ...l, [field]: value } : l)));
  const removeLink = (id: string) => setLinks((prev) => prev.filter((l) => l.id !== id));

  const validate = (): boolean => {
    const next: Record<string, string> = {};
    if (!project.trim()) next.project = 'Project is required.';
    if (!taskTitle.trim()) next.taskTitle = 'Task title is required.';
    if (!description.trim()) next.description = 'Description is required.';
    setErrors(next);
    return Object.keys(next).length === 0;
  };

  const handleSubmit = () => {
    if (!validate()) return;
    const now = new Date().toISOString();
    const item: WorkItem = {
      id: uuid(),
      workId,
      date,
      project: project.trim(),
      client: client.trim() || undefined,
      environment: environment.trim() || undefined,
      category: category || undefined,
      taskTitle: taskTitle.trim(),
      description: description.trim(),
      priority,
      technologies: technologies
        .split(',')
        .map((t) => t.trim())
        .filter(Boolean),
      ticketId: ticketId.trim() || undefined,
      links: links.filter((l) => l.type.trim() && l.url.trim()),
      status: 'Planned',
      sessions: [],
      createdAt: now,
      updatedAt: now,
    };
    onCreate(item);
  };

  return (
    <div className="overlay" role="dialog" aria-modal="true" aria-labelledby="work-plan-title">
      <div className="modal" style={{ width: 640 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <h2 id="work-plan-title" style={{ fontSize: 18 }}>
            Set Today's Work Plan
          </h2>
          <button onClick={onCancel} className="btn btn-ghost btn-sm" aria-label="Close">
            Close
          </button>
        </div>
        <p style={{ color: 'var(--text-muted)', fontSize: 13, marginTop: 4, marginBottom: 4 }}>
          What do you plan to work on? Start time is captured when you press Start, not now.
        </p>

        <div className="form-grid-2" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14, marginTop: 16 }}>
          <div>
            <div className="field-label">Work ID</div>
            <div className="field-static">{workId}</div>
          </div>
          <div>
            <div className="field-label">Date</div>
            <div className="field-static">{date}</div>
          </div>
        </div>

        <div className="form-section-title">Work context</div>
        <div className="form-grid-2" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
          <Field label="Project" required error={errors.project}>
            <input className={`input ${errors.project ? 'input-invalid' : ''}`} value={project} onChange={(e) => setProject(e.target.value)} />
          </Field>
          <Field label="Client" hint="optional">
            <input className="input" value={client} onChange={(e) => setClient(e.target.value)} />
          </Field>
          <Field label="Environment" hint="optional">
            <input className="input" value={environment} onChange={(e) => setEnvironment(e.target.value)} />
          </Field>
          <Field label="Category" hint="optional">
            <select className="select" value={category} onChange={(e) => setCategory(e.target.value as WorkCategory)}>
              <option value="">—</option>
              {WORK_CATEGORIES.map((c) => (
                <option key={c} value={c}>
                  {c}
                </option>
              ))}
            </select>
          </Field>
        </div>

        <div className="form-section-title">Task</div>
        <Field label="Task Title" required error={errors.taskTitle}>
          <input className={`input ${errors.taskTitle ? 'input-invalid' : ''}`} value={taskTitle} onChange={(e) => setTaskTitle(e.target.value)} />
        </Field>
        <Field label="Description" required error={errors.description}>
          <textarea
            className={`textarea ${errors.description ? 'input-invalid' : ''}`}
            style={{ minHeight: 70 }}
            value={description}
            onChange={(e) => setDescription(e.target.value)}
          />
        </Field>

        <div className="form-section-title">Tracking</div>
        <div className="form-grid-2" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
          <Field label="Priority" required>
            <select className="select" value={priority} onChange={(e) => setPriority(e.target.value as WorkPriority)}>
              {WORK_PRIORITIES.map((p) => (
                <option key={p} value={p}>
                  {p}
                </option>
              ))}
            </select>
          </Field>
          <Field label="Ticket / Incident ID" hint="optional">
            <input className="input" value={ticketId} onChange={(e) => setTicketId(e.target.value)} />
          </Field>
        </div>
        <Field label="Technologies" hint="optional, comma-separated">
          <input className="input" value={technologies} onChange={(e) => setTechnologies(e.target.value)} />
        </Field>

        <div className="form-section-title">Resources</div>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <span className="field-label" style={{ margin: 0 }}>
            Links <span className="field-hint">optional</span>
          </span>
          <button onClick={addLink} className="btn btn-ghost btn-sm">
            + Add link
          </button>
        </div>
        {links.map((link) => (
          <div key={link.id} style={{ display: 'flex', gap: 8, marginTop: 8 }}>
            <input
              className="input"
              style={{ width: 130 }}
              placeholder="Type (e.g. Jira)"
              aria-label="Link type"
              value={link.type}
              onChange={(e) => updateLink(link.id, 'type', e.target.value)}
            />
            <input
              className="input"
              style={{ flex: 1 }}
              placeholder="https://..."
              aria-label="Link URL"
              value={link.url}
              onChange={(e) => updateLink(link.id, 'url', e.target.value)}
            />
            <button onClick={() => removeLink(link.id)} className="btn btn-ghost btn-sm" aria-label="Remove link">
              Remove
            </button>
          </div>
        ))}

        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 10, marginTop: 26 }}>
          <button onClick={onCancel} className="btn btn-secondary">
            Cancel
          </button>
          <button onClick={handleSubmit} className="btn btn-primary">
            Create Work Item
          </button>
        </div>
      </div>
    </div>
  );
}

function Field({
  label,
  required,
  error,
  hint,
  children,
}: {
  label: string;
  required?: boolean;
  error?: string;
  hint?: string;
  children: ReactNode;
}) {
  const id = useId();
  return (
    <div className="field">
      <label className="field-label" htmlFor={id}>
        {label}
        {required && <span className="field-required"> *</span>}
        {hint && <span className="field-hint"> · {hint}</span>}
      </label>
      {applyIdToChild(children, id)}
      {error && (
        <div className="field-error" role="alert">
          {error}
        </div>
      )}
    </div>
  );
}

// Lets each Field own its label/htmlFor pairing without every call site
// having to manage its own id.
function applyIdToChild(child: ReactNode, id: string): ReactNode {
  if (isValidElement(child)) {
    return cloneElement(child as ReactElement<{ id?: string }>, { id });
  }
  return child;
}
